golfcourses_app/urls.py
from django.urls import path

from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('courses/', views.index, name='courses-index'),
    path('golfcourses/<int:golfcourse_id>/', views.golfcourse_detail, name='golfcourse-detail'),
    path('courses/create/', views.CourseCreate.as_view(), name='course-create'),
    path('golfcourses/<int:pk>/update/', views.CourseUpdate.as_view(), name='course-update'),
    path('golfcourses/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('golfcourses/<int:golfcourse_id>/add_snack/', views.add_golfsnacks, name='add-golfsnacks'),
]

golfcourses_app/models.py
from django.db import models

from django.urls import reverse
# Create your models here.

class Golf(models.Model):
    name= models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    image = models.ImageField(upload_to='images/golfcourses/', null=True, blank=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("golfcourse-detail", kwargs={"golfcourse_id": self.id})
    
SNACKS = (
    ('C', 'Chips'),
    ('G', 'Glizzy'),
    ('B', 'Burger'),
)

class GolfSnacks(models.Model):
    date = models.DateField('Golf Date')
    snacks = models.CharField(
        max_length=1,
        choices=SNACKS,
        default=SNACKS[0][0]
    )
    
    course = models.ForeignKey(Golf, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return f"{self.get_snack_display()} on {self.date}"

golfcourses_app/forms.py
from django import forms 
from .models import GolfSnacks

class GolfSnacksForm(forms.ModelForm):
    class Meta:
        model = GolfSnacks
        fields = ['date', 'snacks']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

golfcourses_app/views.py
from django.shortcuts import render, redirect
from .models import Golf, GolfSnacks

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.http import HttpResponse

from .forms import GolfSnacksForm

def golfcourse_detail(request, golfcourse_id):
    golfcourses_from_db = Golf.objects.get(id=golfcourse_id)
    snacks = GolfSnacks.objects.filter(course=golfcourses_from_db)
    form = GolfSnacksForm()
    return render(request, 'golfcourses/detail.html', {'golf': golfcourses_from_db, 'snacks': snacks,'form': form})

def add_golfsnacks(request, golfcourse_id):
    golf = Golf.objects.get(id=golfcourse_id)
    form = GolfSnacksForm(request.POST)
    
    if form.is_valid():
        new_snack = form.save(commit=False)
        new_snack.course = golf
        new_snack.save()
        
    return redirect('golfcourse-detail', golfcourse_id=golfcourse_id)

class CourseCreate(CreateView):
    model = Golf
    fields = ['name', 'description']
    template_name = 'main_app/golf_form.html'

class CourseUpdate(UpdateView):
    model = Golf
    fields = ['name', 'description']
    template_name = 'main_app/golf_form.html'
    
class CourseDelete(DeleteView):
    model = Golf
    template_name = 'main_app/golf_confirm_delete.html'
    success_url = '/courses/'



#     def __init__(self, name, description):
#         self.name = name
#         self.description = description



# courses = [
#     Course('Augusta National', 'The Masters Tournament'),
#     Course('Pebble Beach', 'One of the best coastal golf resorts in the world'),
#     Course('TPC Sawgrass', 'The Players Championship'),
#     Course('Emirates Golf Club', 'Omega Dubai Desert Classic')
# ]




def home(request):
    featured_courses = Golf.objects.filter(featured=True)
    return render(request, 'home.html', {'courses': featured_courses})

def about(request):
    return render(request, 'about.html')

def index(request):
    courses = Golf.objects.all() 
    return render(request, 'golfcourses/index.html', {'courses': courses})

golfcourses_app/templates/about.html
{% extends 'base.html' %}



{% block content %}
    <h1>About the Player</h1>
    <hr>
    <p class='page-content'>
        I would like to play all of these courses one day!
    </p>
{% endblock content %}

golfcourses_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Golf Courses</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" type='image/png' href="{% static 'images/golfheader-logo.webp' %}">
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
        <div class="header-logo-container">
          <a href="{% url 'home' %}">Home</a> <!-- Add Home link here -->
        </div>
        <nav>
          <ul>
              <li><a href="{% url 'courses-index' %}">All Golf Courses</a></li>
              <li><a href="{% url 'course-create' %}">Add Golf Courses</a></li>  
              <li><a href="{% url 'about' %}">About</a></li>
          </ul>
        </nav>
      </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

golfcourses_app/templates/golfcourses/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/courses/golfcourse-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="golfcourse-container">
  <div class="golf-img">
    {% if golf.image %}
      <img src="{{ golf.image.url }}" alt="{{ golf.name }}">
    {% else %}
      <img src="{% static 'images/golfheader-logo.webp' %}" alt="Default Image">
    {% endif %}
  </div>
  <div class="golfcourse-details">
    <h1>{{ golf.name }}</h1>
    <p>{{ golf.description }}</p>
    <div class="golf-actions">
      <a href="{% url 'course-update' golf.id %}" class="btn warn">Edit</a>
      <a href="{% url 'course-delete' golf.id %}" class="btn danger">Delete</a>
    </div>
    <div class="snack-box">
      <h2>Snacks</h2>
      {% if snacks %}
        <ul>
          {% for snack in snacks %}
            <li>{{ snack.get_snacks_display }} on {{ snack.date }}</li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No snacks available for this course.</p>
      {% endif %}
  </div>
  <div class="snack-form">
    <h3>Add a Snack</h3>
    <form action="{% url 'add-golfsnacks' golf.id %}" method="post">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }} 
      <button type="submit" class="btn">Add Snack</button>
    </form>
  </div>
</section>
{% endblock %}

golfcourses_app/templates/golfcourses/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/courses/course-index.css' %}">
{% endblock head %}

{% block content %}
    

<section class='card-container'>
    
    {% for course in courses  %}
        <div class='card'>
            <a href="{% url 'golfcourse-detail' course.id %}">
                <div class="card-img-container">
                    {% if course.image %}
                        <img src="{{ course.image.url }}" alt="{{ course.name }}">
                    {% else %}
                        <img src="{% static 'images/golfheader-logo.webp' %}" alt="Default Image"> 
                    {% endif %}
                </div>
            <h2 class='card-title'>{{ course.name }}</h2>

            <p><small>{{ course.description }}</small></p>
                
        </div>
    </a>
    {% endfor %}
        

</section>

{% endblock content %}

golfcourses_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/courses/course-index.css' %}">
{% endblock head %}

{% block content %}
<section class='page-header'>
    <h1>Featured Golf Courses</h1>
</section>

<section class='card-container'>
    <div class='card'>
        <a href="{% url 'golfcourse-detail' 1 %}"> 
            <div class="card-img-container">
                <img src="{% static 'images/Augusta.png' %}" alt="Augusta National">
            </div>
            <h2 class='card-title'>Augusta National</h2>
            <p><small>The Masters Tournament</small></p>
        </a>
    </div>

    <div class='card'>
        <a href="{% url 'golfcourse-detail' 2 %}"> 
            <div class="card-img-container">
                <img src="{% static 'images/Emirates Golf Club.png' %}" alt="Emirates Golf Club">
            </div>
            <h2 class='card-title'>Emirates Golf Club</h2>
            <p><small>Omega Dubai Desert Classic</small></p>
        </a>
    </div>

    <div class='card'>
        <a href="{% url 'golfcourse-detail' 3 %}"> 
            <div class="card-img-container">
                <img src="{% static 'images/Pebble Beach.png' %}" alt="Pebble Beach">
            </div>
            <h2 class='card-title'>Pebble Beach</h2>
            <p><small>One of the best coastal golf resorts in the world</small></p>
        </a>
    </div>

    <div class='card'>
        <a href="{% url 'golfcourse-detail' 4 %}"> 
            <div class="card-img-container">
                <img src="{% static 'images/TPC Sawgrass.png' %}" alt="TPC Sawgrass">
            </div>
            <h2 class='card-title'>TPC Sawgrass</h2>
            <p><small>The Players Championship</small></p>
        </a>
    </div>
</section>
{% endblock content %}

golfcourses_app/templates/main_app/golf_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h2>Are you sure you want to delete {{ golf.name }}?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn danger">Confirm Delete</button>
    <a href="{% url 'golfcourse-detail' golf.id %}" class="btn">Cancel</a>
</form>
{% endblock %}

golfcourses_app/templates/main_app/golf_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  <h1>Add Golf Course</h1>
  <img src="{% static 'images/golfheader-logo.webp' %}" alt="A golf ball" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}